scss_files: 'src/scss'

exclude: 'src/scss/_normalize.scss'

linters:
  SelectorFormat:
    enabled: false

  # Indentation:
  #   exclude:
  #     - 'path/to/file.scss'
  #     - 'path/to/directory/**'
  #   severity: warning
  #   width: 2